FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
ADD ./ /code
CMD /wait.sh db 5432 \
  && python3 CreeTutorBackend/manage.py collectstatic --noinput \
  && python3 CreeTutorBackend/manage.py migrate \
  && python3 CreeTutorBackend/manage.py loaddata db_init.json \
  && /usr/local/bin/uwsgi --ini /CreeTutor/CreeTutorBackend/CreeTutorBackend/uwsgi.ini