# Generated by Django 2.0.5 on 2018-07-10 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('name', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('vowel', models.TextField(blank=True, null=True)),
                ('sound', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alphabet',
            },
        ),
        migrations.CreateModel(
            name='DoubleLetterStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('chosen_answer', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('time_answered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'double_letter_stats',
            },
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lemma', models.CharField(blank=True, max_length=255, null=True)),
                ('useable_gram_codes', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.CharField(blank=True, max_length=8, null=True)),
                ('animate', models.CharField(blank=True, max_length=8, null=True)),
                ('transitive', models.CharField(blank=True, max_length=8, null=True)),
                ('translation', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'lemma',
            },
        ),
        migrations.CreateModel(
            name='LetterPair',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('first_letter', models.CharField(blank=True, max_length=2, null=True)),
                ('second_letter', models.CharField(blank=True, max_length=2, null=True)),
                ('sound', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'letter_pair',
            },
        ),
        migrations.CreateModel(
            name='SingleLetterStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('chosen_answer', models.CharField(blank=True, max_length=4, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=4, null=True)),
                ('time_answered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'single_letter_stats',
            },
        ),
        migrations.CreateModel(
            name='SoundInSyllable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syl_id', models.IntegerField(blank=True, null=True)),
                ('pair', models.CharField(blank=True, max_length=8, null=True)),
                ('vowel', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'sound_in_syllable',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('gram_code', models.CharField(blank=True, max_length=100, null=True)),
                ('translation', models.TextField(blank=True, null=True)),
                ('num_syllables', models.IntegerField(blank=True, null=True)),
                ('lemma_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lettergame.Lemma')),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.CreateModel(
            name='WordSyllable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(blank=True, null=True)),
                ('syllable_num', models.IntegerField(blank=True, null=True)),
                ('syllable_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'word_syllable',
            },
        ),
    ]
