# Generated by Django 2.0.5 on 2018-07-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettergame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='lemma_id',
            new_name='lemmaID',
        ),
    ]
