# Generated by Django 2.0.5 on 2018-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettergame', '0002_auto_20180611_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterGameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('answer_chosen', models.CharField(blank=True, max_length=4, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'letter_game_stats',
                'managed': False,
            },
        ),
    ]
