# Generated by Django 2.0.5 on 2018-07-10 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lettergame', '0002_auto_20180710_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animate',
            fields=[
                ('animate', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'animate',
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('pos', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'part_of_speech',
            },
        ),
        migrations.CreateModel(
            name='Transitive',
            fields=[
                ('transitive', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'transitive',
            },
        ),
        migrations.AlterField(
            model_name='lemma',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lettergame.PartOfSpeech'),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='transitive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lettergame.Transitive'),
        ),
    ]
