# Generated by Django 2.0.5 on 2018-07-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lettergame', '0003_auto_20180710_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='animate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lettergame.Animate'),
        ),
    ]
