# Generated by Django 2.0.5 on 2018-06-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettergame', '0003_lettergamestats'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lettergamestats',
            table='lettergame_stats',
        ),
    ]
