# Generated by Django 2.0.5 on 2018-07-10 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lettergame', '0004_auto_20180710_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='GramCode',
            fields=[
                ('gram_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'game_code',
            },
        ),
        migrations.AlterField(
            model_name='lemma',
            name='useable_gram_codes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lettergame.GramCode'),
        ),
        migrations.AlterField(
            model_name='word',
            name='gram_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lettergame.GramCode'),
        ),
    ]
