# Generated by Django 2.0.5 on 2018-06-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettergame', '0004_auto_20180615_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterPairs',
            fields=[
                ('pair', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('first_letter', models.CharField(blank=True, max_length=2, null=True)),
                ('second_letter', models.CharField(blank=True, max_length=2, null=True)),
                ('sound', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'letter_pairs',
                'managed': False,
            },
        ),
    ]
