# Generated by Django 2.0.5 on 2018-06-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettergame', '0005_letterpairs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairletterStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('chosen_answer', models.CharField(blank=True, max_length=6, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=6, null=True)),
                ('time_answered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pairletter_stats',
                'managed': False,
            },
        ),
    ]
