# Generated by Django 2.0.5 on 2018-07-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettergame', '0005_auto_20180710_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alphabet',
            old_name='name',
            new_name='letter',
        ),
        migrations.RenameField(
            model_name='letterpair',
            old_name='name',
            new_name='pair',
        ),
    ]
